version: '3.9'
services:
  todolist_db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
    ports:
      - '5432:5432'
    volumes:
      - todolist_db:/var/lib/postgresql/data

volumes:
  todolist_db: