version: '3.9'
services:
  front:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    restart: always
    image: vmonin/todolist_dp
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8000:8000'


  postgres:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend


volumes:
  db:

networks:
  backend:
    driver: bridge