# Generated by Django 4.1.5 on 2023-01-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_deleted',
        ),
    ]
